name: Node.js Build, Artifact Upload, and Docker Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js 21
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'  # Caches `node_modules` automatically

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Pre-build phase
      - name: Pre-build step
        run: echo "Installing source NPM dependencies..."

      # Build phase (optional)
      - name: Build project
        id: build
        run: |
          echo "Build started on $(date)"
          if npm run build; then
            echo "Build completed successfully"
          else
            echo "No build script found, skipping build"
          fi
          npm prune --production

      # Post-build phase
      - name: Post-build step
        run: echo "Post-build steps completed on $(date)"

      # Upload artifacts (optional, if you want to store the build output)
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            ./dist/**      # Replace 'dist' with your actual output directory if needed
            !**/*:*        # Exclude files with invalid characters

      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}  # Replace with your Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Replace with your Docker Hub password secret

      # Step 7: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

      # Step 8: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
